[tool.black]
line-length = 88

[tool.poetry]
name = "managed-services-integration-tests"
version = "1.0"
description = "managed-services-integration-tests"
authors = ["managed-services-integration-tests"]

[tool.poetry.dependencies]
python = "^3.9"
pytest-progress = "==1.2.5"  # https://github.com/ssrikanta/pytest-progress
openshift-python-wrapper = "^4.14.1"
docker = "^6.1.3"
colorlog = "^6.7.0"
openshift-python-utilities = "^4.14.2"
openshift-cluster-management-python-wrapper = "^1.0.27"
openshift-python-wrapper-data-collector = "^1.0.4"
pytest = "^7.4.0"
pytest-testconfig = "^0.2.0"
hvac = "^1.1.1"
pytz = "^2023.3"
pip = "^23.1.2"
pyyaml = "^6.0"
rhoas-sdks = "^1.0.5"
auth = "^0.5.3"
python-terraform = "^0.10.1"
pytest-dependency = "^0.5.1"
pytest-order = "^1.1.0"
shortuuid = "^1.0.11"
redhat-qe-cloud-tools = "^1.0.9"
boto3 = "^1.28.1"
rosa-python-client = "^1.0.16"
python-simple-logger = "^1.0.5"
packaging = "^23.1"
pyaml-env = "^1.2.1"
openshift-cli-installer = "^1.0.2"

[tool.poetry.dev-dependencies]
ipdb = "*"
ipython = "*"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
